In [1]:
import pandas as pd
from functions.eval import *

In [2]:
model_pred_col = "Camelbert-MSA"
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa-sentiment"
# model_name = "PRAli22/AraBert-Arabic-Sentiment-Analysis"
# model_pred_col = "AraBert"

In [3]:
lime_eval = pd.read_csv("data/xai_eval/xai_eval_lime_" + model_pred_col + ".csv")
shap_eval = pd.read_csv("data/xai_eval/xai_eval_shap_" + model_pred_col + ".csv")
ig_eval = pd.read_csv("data/xai_eval/xai_eval_ig_" + model_pred_col + ".csv")
dl_eval = pd.read_csv("data/xai_eval/xai_eval_dl_" + model_pred_col + ".csv")
ensemble_eval = pd.read_csv("data/xai_eval/xai_eval_ensemble_" + model_pred_col + ".csv")

In [4]:
eval_df = pd.concat([lime_eval, shap_eval, ig_eval, dl_eval, ensemble_eval], axis=1)

In [5]:
XAI_methods = ["LIME", "SHAP", "IG", "DeepLIFT", "EXAI_LIME_SHAP_IG_DL_mean", 
               "EXAI_LIME_SHAP_IG_DL_median", "EXAI_LIME_SHAP_IG_mean", 
               "EXAI_LIME_SHAP_IG_median", "EXAI_LIME_SHAP_mean"]
metrics = ["comprehensiveness", "sufficiency", "corr_loo", "ins_AUC", "del_AUC", "combined"]

In [6]:
df = pd.DataFrame(
    {metric: [] for metric in metrics},
)

In [7]:
for xai_method in XAI_methods:
    for metric in metrics:
        col_name = f"{xai_method}_{metric}"
        if col_name in eval_df.columns:
            df.loc[xai_method, metric] = eval_df[col_name].mean()
        else:
            df.loc[xai_method, metric] = None

In [8]:
borda_count(df)

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined,borda
LIME,0.483079,0.286548,0.306868,0.630709,0.400346,0.616093,26
SHAP,0.452836,0.288878,0.254666,0.635663,0.417806,0.601830,34
IG,0.422995,0.198649,0.138863,0.584349,0.476752,0.580275,37
DeepLIFT,0.425567,0.138952,0.003353,0.536765,0.534167,0.558178,36
EXAI_LIME_SHAP_IG_DL_mean,0.497280,0.175490,0.286747,0.632149,0.406590,0.638143,18
EXAI_LIME_SHAP_IG_DL_median,0.491069,0.189190,0.283323,0.630914,0.408905,0.633105,23
EXAI_LIME_SHAP_IG_mean,0.482913,0.254283,0.317555,0.639124,0.395649,0.626177,16
EXAI_LIME_SHAP_IG_median,0.478428,0.264484,0.309480,0.636583,0.400371,0.620979,22
EXAI_LIME_SHAP_mean,0.486974,0.277657,0.325440,0.642922,0.392192,0.624629,13

In [9]:
df_std = df.copy()
for xai_method in XAI_methods:
    for metric in metrics:
        col_name = f"{xai_method}_{metric}"
        if col_name in eval_df.columns:
            df_std.loc[xai_method, metric] = eval_df[col_name].std()
        else:
            df_std.loc[xai_method, metric] = None

In [10]:
df_std.drop(columns=["borda"], inplace=True)
df_std

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined
LIME,0.330689,0.362066,0.211706,0.155009,0.205434,0.096867
SHAP,0.319674,0.354744,0.231218,0.157114,0.194704,0.101493
IG,0.344318,0.322902,0.204780,0.170387,0.202044,0.116241
DeepLIFT,0.357555,0.270424,0.210588,0.184433,0.187246,0.115595
EXAI_LIME_SHAP_IG_DL_mean,0.330876,0.322990,0.204300,0.156250,0.200264,0.101748
EXAI_LIME_SHAP_IG_DL_median,0.332787,0.329717,0.205829,0.156118,0.200692,0.102533
EXAI_LIME_SHAP_IG_mean,0.333420,0.354432,0.206413,0.154278,0.198800,0.099663
EXAI_LIME_SHAP_IG_median,0.333558,0.362826,0.214305,0.154462,0.199983,0.101186
EXAI_LIME_SHAP_mean,0.329738,0.361411,0.217538,0.153897,0.198359,0.097445

In [11]:
# model_pred_col = "Camelbert-MSA"
# model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa-sentiment"
model_name = "PRAli22/AraBert-Arabic-Sentiment-Analysis"
model_pred_col = "AraBert"

In [12]:
lime_eval = pd.read_csv("data/xai_eval/xai_eval_lime_" + model_pred_col + ".csv")
shap_eval = pd.read_csv("data/xai_eval/xai_eval_shap_" + model_pred_col + ".csv")
ig_eval = pd.read_csv("data/xai_eval/xai_eval_ig_" + model_pred_col + ".csv")
dl_eval = pd.read_csv("data/xai_eval/xai_eval_dl_" + model_pred_col + ".csv")
ensemble_eval = pd.read_csv("data/xai_eval/xai_eval_ensemble_" + model_pred_col + ".csv")

In [13]:
eval_df = pd.concat([lime_eval, shap_eval, ig_eval, dl_eval, ensemble_eval], axis=1)

In [14]:
XAI_methods = ["LIME", "SHAP", "IG", "DeepLIFT", "EXAI_LIME_SHAP_IG_DL_mean", 
               "EXAI_LIME_SHAP_IG_DL_median", "EXAI_LIME_SHAP_IG_mean", 
               "EXAI_LIME_SHAP_IG_median", "EXAI_LIME_SHAP_mean"]
metrics = ["comprehensiveness", "sufficiency", "corr_loo", "ins_AUC", "del_AUC", "combined"]

In [15]:
df2 = pd.DataFrame(
    {metric: [] for metric in metrics},
)

In [16]:
for xai_method in XAI_methods:
    for metric in metrics:
        col_name = f"{xai_method}_{metric}"
        if col_name in eval_df.columns:
            df2.loc[xai_method, metric] = eval_df[col_name].mean()
        else:
            df2.loc[xai_method, metric] = None

In [17]:
borda_count(df2)

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined,borda
LIME,0.408192,-0.041818,0.341344,0.796975,0.380106,0.707554,21
SHAP,0.394056,-0.056610,0.291647,0.800246,0.378840,0.703579,23
IG,0.304511,0.038786,0.126209,0.700850,0.525548,0.600826,40
DeepLIFT,0.233068,0.098759,0.020018,0.629802,0.610987,0.532627,45
EXAI_LIME_SHAP_IG_DL_mean,0.399298,-0.039098,0.290597,0.789550,0.396600,0.695381,31
EXAI_LIME_SHAP_IG_DL_median,0.397023,-0.036980,0.295454,0.789733,0.396654,0.695014,31
EXAI_LIME_SHAP_IG_mean,0.418742,-0.051656,0.329318,0.802361,0.370630,0.713358,14
EXAI_LIME_SHAP_IG_median,0.413092,-0.045647,0.334243,0.802513,0.373185,0.711038,15
EXAI_LIME_SHAP_mean,0.423356,-0.059785,0.351896,0.810686,0.354560,0.723153,5

In [18]:
df_std2 = df2.copy()
for xai_method in XAI_methods:
    for metric in metrics:
        col_name = f"{xai_method}_{metric}"
        if col_name in eval_df.columns:
            df_std2.loc[xai_method, metric] = eval_df[col_name].std()
        else:
            df_std2.loc[xai_method, metric] = None

In [19]:
df_std2.drop(columns=["borda"], inplace=True)
df_std2

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined
LIME,0.258828,0.158096,0.221943,0.142936,0.208908,0.093053
SHAP,0.257754,0.150534,0.227625,0.134855,0.197866,0.088936
IG,0.282224,0.181444,0.214802,0.188182,0.218464,0.107151
DeepLIFT,0.286466,0.222530,0.209458,0.208783,0.211034,0.110779
EXAI_LIME_SHAP_IG_DL_mean,0.259237,0.144960,0.201387,0.145250,0.204477,0.087016
EXAI_LIME_SHAP_IG_DL_median,0.261082,0.152407,0.204855,0.145069,0.206620,0.089118
EXAI_LIME_SHAP_IG_mean,0.253990,0.142997,0.209538,0.138740,0.197603,0.086880
EXAI_LIME_SHAP_IG_median,0.256884,0.149087,0.218063,0.138023,0.201575,0.088803
EXAI_LIME_SHAP_mean,0.252721,0.142735,0.218976,0.134361,0.195520,0.086464

In [20]:
df_avg = (df + df2) / 2
borda_count(df_avg)

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined,borda
LIME,0.445635,0.122365,0.324106,0.713842,0.390226,0.661823,25
SHAP,0.423446,0.116134,0.273157,0.717954,0.398323,0.652704,29
IG,0.363753,0.118718,0.132536,0.642599,0.501150,0.590550,39
DeepLIFT,0.329318,0.118855,0.011685,0.583283,0.572577,0.545402,44
EXAI_LIME_SHAP_IG_DL_mean,0.448289,0.068196,0.288672,0.710850,0.401595,0.666762,22
EXAI_LIME_SHAP_IG_DL_median,0.444046,0.076105,0.289389,0.710324,0.402780,0.664059,27
EXAI_LIME_SHAP_IG_mean,0.450828,0.101313,0.323437,0.720743,0.383140,0.669767,12
EXAI_LIME_SHAP_IG_median,0.445760,0.109419,0.321862,0.719548,0.386778,0.666008,19
EXAI_LIME_SHAP_mean,0.455165,0.108936,0.338668,0.726804,0.373376,0.673891,8

In [21]:
df_std_avg = (df_std + df_std2) / 2
df_std_avg

,comprehensiveness,sufficiency,corr_loo,ins_AUC,del_AUC,combined
LIME,0.294759,0.260081,0.216825,0.148973,0.207171,0.094960
SHAP,0.288714,0.252639,0.229422,0.145984,0.196285,0.095215
IG,0.313271,0.252173,0.209791,0.179284,0.210254,0.111696
DeepLIFT,0.322010,0.246477,0.210023,0.196608,0.199140,0.113187
EXAI_LIME_SHAP_IG_DL_mean,0.295057,0.233975,0.202843,0.150750,0.202371,0.094382
EXAI_LIME_SHAP_IG_DL_median,0.296935,0.241062,0.205342,0.150594,0.203656,0.095826
EXAI_LIME_SHAP_IG_mean,0.293705,0.248715,0.207975,0.146509,0.198201,0.093271
EXAI_LIME_SHAP_IG_median,0.295221,0.255956,0.216184,0.146242,0.200779,0.094994
EXAI_LIME_SHAP_mean,0.291230,0.252073,0.218257,0.144129,0.196940,0.091954

Spearman rank correlation between the Combined metric and Borda count rankings

In [22]:
from scipy import stats

In [26]:
corr, pval = stats.spearmanr(df_avg["combined"], df_avg["borda"])
corr, pval

(np.float64(-0.9666666666666667), np.float64(2.155031274835775e-05))

Leave-one-metric-out

In [35]:
metric_to_leave_out = "comprehensiveness"
df_avg["combined"] = df_avg.apply(lambda row: combined_metric(comp=None, suff=row["sufficiency"], corr_loo=row["corr_loo"], ins_auc=row["ins_AUC"], del_auc=row["del_AUC"]), axis=1)
borda_count_leave_one_out(df_avg.drop(columns=[metric_to_leave_out]), metric_to_leave_out=metric_to_leave_out)

,sufficiency,corr_loo,ins_AUC,del_AUC,combined,borda
LIME,0.122365,0.324106,0.713842,0.390226,0.715826,20
SHAP,0.116134,0.273157,0.717954,0.398323,0.710019,22
IG,0.118718,0.132536,0.642599,0.501150,0.647250,31
DeepLIFT,0.118855,0.011685,0.583283,0.572577,0.599423,35
EXAI_LIME_SHAP_IG_DL_mean,0.068196,0.288672,0.710850,0.401595,0.721349,19
EXAI_LIME_SHAP_IG_DL_median,0.076105,0.289389,0.710324,0.402780,0.719033,21
EXAI_LIME_SHAP_IG_mean,0.101313,0.323437,0.720743,0.383140,0.724502,10
EXAI_LIME_SHAP_IG_median,0.109419,0.321862,0.719548,0.386778,0.721070,15
EXAI_LIME_SHAP_mean,0.108936,0.338668,0.726804,0.373376,0.728457,7

In [36]:
metric_to_leave_out = "sufficiency"
df_avg["combined"] = df_avg.apply(lambda row: combined_metric(comp=row["comprehensiveness"], suff=None, corr_loo=row["corr_loo"], ins_auc=row["ins_AUC"], del_auc=row["del_AUC"]), axis=1)
borda_count_leave_one_out(df_avg.drop(columns=[metric_to_leave_out]), metric_to_leave_out=metric_to_leave_out)

,comprehensiveness,corr_loo,ins_AUC,del_AUC,combined,borda
LIME,0.445635,0.324106,0.713842,0.390226,0.607826,16
SHAP,0.423446,0.273157,0.717954,0.398323,0.594914,23
IG,0.363753,0.132536,0.642599,0.501150,0.517867,32
DeepLIFT,0.329318,0.011685,0.583283,0.572577,0.461467,36
EXAI_LIME_SHAP_IG_DL_mean,0.448289,0.288672,0.710850,0.401595,0.600470,21
EXAI_LIME_SHAP_IG_DL_median,0.444046,0.289389,0.710324,0.402780,0.599071,25
EXAI_LIME_SHAP_IG_mean,0.450828,0.323437,0.720743,0.383140,0.612537,9
EXAI_LIME_SHAP_IG_median,0.445760,0.321862,0.719548,0.386778,0.609865,14
EXAI_LIME_SHAP_mean,0.455165,0.338668,0.726804,0.373376,0.619482,4

In [37]:
metric_to_leave_out = "corr_loo"
df_avg["combined"] = df_avg.apply(lambda row: combined_metric(comp=row["comprehensiveness"], suff=row["sufficiency"], corr_loo=None, ins_auc=row["ins_AUC"], del_auc=row["del_AUC"]), axis=1)
borda_count_leave_one_out(df_avg.drop(columns=[metric_to_leave_out]), metric_to_leave_out=metric_to_leave_out)

,comprehensiveness,sufficiency,ins_AUC,del_AUC,combined,borda
LIME,0.445635,0.122365,0.713842,0.390226,0.661722,23
SHAP,0.423446,0.116134,0.717954,0.398323,0.656736,22
IG,0.363753,0.118718,0.642599,0.501150,0.596621,31
DeepLIFT,0.329318,0.118855,0.583283,0.572577,0.555292,35
EXAI_LIME_SHAP_IG_DL_mean,0.448289,0.068196,0.710850,0.401595,0.672337,16
EXAI_LIME_SHAP_IG_DL_median,0.444046,0.076105,0.710324,0.402780,0.668871,22
EXAI_LIME_SHAP_IG_mean,0.450828,0.101313,0.720743,0.383140,0.671779,9
EXAI_LIME_SHAP_IG_median,0.445760,0.109419,0.719548,0.386778,0.667278,15
EXAI_LIME_SHAP_mean,0.455165,0.108936,0.726804,0.373376,0.674914,7

In [38]:
metric_to_leave_out = "ins_AUC"
df_avg["combined"] = df_avg.apply(lambda row: combined_metric(comp=row["comprehensiveness"], suff=row["sufficiency"], corr_loo=row["corr_loo"], ins_auc=None, del_auc=row["del_AUC"]), axis=1)
borda_count_leave_one_out(df_avg.drop(columns=[metric_to_leave_out]), metric_to_leave_out=metric_to_leave_out)

,comprehensiveness,sufficiency,corr_loo,del_AUC,combined,borda
LIME,0.445635,0.122365,0.324106,0.390226,0.648774,20
SHAP,0.423446,0.116134,0.273157,0.398323,0.636392,25
IG,0.363753,0.118718,0.132536,0.501150,0.577538,31
DeepLIFT,0.329318,0.118855,0.011685,0.572577,0.535932,35
EXAI_LIME_SHAP_IG_DL_mean,0.448289,0.068196,0.288672,0.401595,0.655709,16
EXAI_LIME_SHAP_IG_DL_median,0.444046,0.076105,0.289389,0.402780,0.652464,20
EXAI_LIME_SHAP_IG_mean,0.450828,0.101313,0.323437,0.383140,0.657023,10
EXAI_LIME_SHAP_IG_median,0.445760,0.109419,0.321862,0.386778,0.652623,16
EXAI_LIME_SHAP_mean,0.455165,0.108936,0.338668,0.373376,0.660547,7

In [39]:
metric_to_leave_out = "del_AUC"
df_avg["combined"] = df_avg.apply(lambda row: combined_metric(comp=row["comprehensiveness"], suff=row["sufficiency"], corr_loo=row["corr_loo"], ins_auc=row["ins_AUC"], del_auc=None), axis=1)
borda_count_leave_one_out(df_avg.drop(columns=[metric_to_leave_out]), metric_to_leave_out=metric_to_leave_out)

,comprehensiveness,sufficiency,corr_loo,ins_AUC,combined,borda
LIME,0.445635,0.122365,0.324106,0.713842,0.674791,21
SHAP,0.423446,0.116134,0.273157,0.717954,0.665461,24
IG,0.363753,0.118718,0.132536,0.642599,0.613476,31
DeepLIFT,0.329318,0.118855,0.011685,0.583283,0.574897,35
EXAI_LIME_SHAP_IG_DL_mean,0.448289,0.068196,0.288672,0.710850,0.683820,16
EXAI_LIME_SHAP_IG_DL_median,0.444046,0.076105,0.289389,0.710324,0.680740,20
EXAI_LIME_SHAP_IG_mean,0.450828,0.101313,0.323437,0.720743,0.682994,10
EXAI_LIME_SHAP_IG_median,0.445760,0.109419,0.321862,0.719548,0.679205,16
EXAI_LIME_SHAP_mean,0.455165,0.108936,0.338668,0.726804,0.685592,7