In [1]:
import pandas as pd
from functions.eval import *

In [2]:
model_pred_col = "Camelbert-MSA"
model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa-sentiment"
# model_name = "PRAli22/AraBert-Arabic-Sentiment-Analysis"
# model_pred_col = "AraBert"

In [3]:
eval_df = pd.read_csv("data/hard_rationale/hard_rationale_ensemble_" + model_pred_col + ".csv")

In [4]:
hard_rationale_choices = ["elbow_simple-lmethod", "elbow_kneedle", "elbow_dfdt", "elbow_lmethod",
                          "top_n_3", "top_n_5", "top_n_10", "top_n_20", 
                          "threshold_0.1", "threshold_0.3", "threshold_0.5", "threshold_0.7"]
metrics = ["comprehensiveness", "sufficiency", "combined"]

In [5]:
df = pd.DataFrame(
    {metric: [] for metric in metrics},
)

In [6]:
for hr in hard_rationale_choices:
    for metric in metrics:
        col_name = f"EXAI_LIME_SHAP_mean_{hr}_{metric}"
        if col_name in eval_df.columns:
            df.loc[hr, metric] = eval_df[col_name].mean()
        else:
            df.loc[hr, metric] = None

In [7]:
df = borda_count_hard_rationale(df)

In [8]:
for hr in hard_rationale_choices:
    col_name = f"nb_selected_tokens_{hr}"
    col2_name = f"%_tokens_input_{hr}"
    if col_name in eval_df.columns:
        df.loc[hr, "avg_nb_selected_tokens"] = eval_df[col_name].mean()
    else:
        df.loc[hr, "avg_nb_selected_tokens"] = None
    if col2_name in eval_df.columns:
        df.loc[hr, "avg_%_tokens_input"] = eval_df[col2_name].mean()
    else:
        df.loc[hr, "avg_%_tokens_input"] = None
df

,comprehensiveness,sufficiency,combined,borda,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.484616,0.277315,0.603650,9,12.223211,0.514527
elbow_kneedle,0.489675,0.317828,0.585924,9,9.434883,0.419887
elbow_dfdt,0.500552,0.181473,0.659540,5,13.143752,0.574051
elbow_lmethod,0.411377,0.458668,0.476354,16,3.886581,0.207729
top_n_3,0.367703,0.470711,0.448496,20,2.998351,0.173043
top_n_5,0.455276,0.416650,0.519313,14,4.984174,0.284201
top_n_10,0.505988,0.263695,0.621147,5,9.729970,0.526198
top_n_20,0.557342,0.052498,0.752422,2,17.135839,0.830945
threshold_0.1,0.478886,0.394724,0.542081,12,7.279591,0.325445
threshold_0.3,0.402677,0.458959,0.471859,18,4.594791,0.214084
threshold_0.5,0.308894,0.495533,0.406681,22,2.580613,0.127401
threshold_0.7,0.222872,0.525670,0.348601,24,1.326080,0.072048

In [9]:
df_std = df.copy()
for hr in hard_rationale_choices:
    for metric in metrics:
        col_name = f"EXAI_LIME_SHAP_mean_{hr}_{metric}"
        if col_name in eval_df.columns:
            df_std.loc[hr, metric] = eval_df[col_name].std()
        else:
            df_std.loc[hr, metric] = None
df_std.drop(columns=["borda"], inplace=True)
for hr in hard_rationale_choices:
    col_name = f"nb_selected_tokens_{hr}"
    col2_name = f"%_tokens_input_{hr}"
    if col_name in eval_df.columns:
        df_std.loc[hr, "avg_nb_selected_tokens"] = eval_df[col_name].std()
    else:
        df_std.loc[hr, "avg_nb_selected_tokens"] = None
    if col2_name in eval_df.columns:
        df_std.loc[hr, "avg_%_tokens_input"] = eval_df[col2_name].std()
    else:
        df_std.loc[hr, "avg_%_tokens_input"] = None
df_std

,comprehensiveness,sufficiency,combined,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.329879,0.361269,0.210747,10.903902,0.346384
elbow_kneedle,0.310144,0.357418,0.203729,7.736282,0.251159
elbow_dfdt,0.314263,0.344586,0.215376,9.939980,0.300176
elbow_lmethod,0.317357,0.333498,0.217068,1.930093,0.132347
top_n_3,0.315368,0.335126,0.222686,0.040575,0.119311
top_n_5,0.315858,0.336170,0.221921,0.173472,0.177168
top_n_10,0.282012,0.322911,0.175150,1.032430,0.238652
top_n_20,0.292355,0.199040,0.147487,4.327157,0.182876
threshold_0.1,0.292350,0.341435,0.186658,5.648596,0.193678
threshold_0.3,0.303705,0.334337,0.213404,3.792916,0.146682
threshold_0.5,0.295229,0.335629,0.223352,2.101368,0.096799
threshold_0.7,0.271309,0.338798,0.220846,1.022263,0.066547

In [12]:
# model_pred_col = "Camelbert-MSA"
# model_name = "CAMeL-Lab/bert-base-arabic-camelbert-msa-sentiment"
model_name = "PRAli22/AraBert-Arabic-Sentiment-Analysis"
model_pred_col = "AraBert"

In [13]:
eval_df = pd.read_csv("data/hard_rationale/hard_rationale_ensemble_" + model_pred_col + ".csv")

In [14]:
hard_rationale_choices = ["elbow_simple-lmethod", "elbow_kneedle", "elbow_dfdt", "elbow_lmethod",
                          "top_n_3", "top_n_5", "top_n_10", "top_n_20", 
                          "threshold_0.1", "threshold_0.3", "threshold_0.5", "threshold_0.7"]
metrics = ["comprehensiveness", "sufficiency", "combined"]

In [15]:
df2 = pd.DataFrame(
    {metric: [] for metric in metrics},
)

In [16]:
for hr in hard_rationale_choices:
    for metric in metrics:
        col_name = f"EXAI_LIME_SHAP_mean_{hr}_{metric}"
        if col_name in eval_df.columns:
            df2.loc[hr, metric] = eval_df[col_name].mean()
        else:
            df2.loc[hr, metric] = None

In [17]:
df2 = borda_count_hard_rationale(df2)

In [18]:
for hr in hard_rationale_choices:
    col_name = f"nb_selected_tokens_{hr}"
    col2_name = f"%_tokens_input_{hr}"
    if col_name in eval_df.columns:
        df2.loc[hr, "avg_nb_selected_tokens"] = eval_df[col_name].mean()
    else:
        df2.loc[hr, "avg_nb_selected_tokens"] = None
    if col2_name in eval_df.columns:
        df2.loc[hr, "avg_%_tokens_input"] = eval_df[col2_name].mean()
    else:
        df2.loc[hr, "avg_%_tokens_input"] = None
df2

,comprehensiveness,sufficiency,combined,borda,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.423435,-0.059635,0.741535,10,11.509067,0.523895
elbow_kneedle,0.409545,-0.080528,0.745036,8,9.067590,0.430677
elbow_dfdt,0.460109,-0.072106,0.766107,7,12.556874,0.588528
elbow_lmethod,0.282125,-0.066519,0.674322,14,3.960765,0.226215
top_n_3,0.239220,-0.054659,0.646939,18,2.997362,0.186902
top_n_5,0.317955,-0.093797,0.705876,9,4.976921,0.305183
top_n_10,0.417943,-0.094623,0.756283,5,9.658424,0.556800
top_n_20,0.482955,-0.048694,0.765824,11,16.682163,0.856756
threshold_0.1,0.367872,-0.077910,0.722891,10,7.188922,0.346919
threshold_0.3,0.280893,-0.052990,0.666942,18,4.698648,0.235287
threshold_0.5,0.204979,-0.002903,0.603941,22,2.794263,0.148008
threshold_0.7,0.145512,0.097962,0.523775,24,1.469172,0.085134

In [19]:
df_std2 = df2.copy()
for hr in hard_rationale_choices:
    for metric in metrics:
        col_name = f"EXAI_LIME_SHAP_mean_{hr}_{metric}"
        if col_name in eval_df.columns:
            df_std2.loc[hr, metric] = eval_df[col_name].std()
        else:
            df_std2.loc[hr, metric] = None
df_std2.drop(columns=["borda"], inplace=True)
for hr in hard_rationale_choices:
    col_name = f"nb_selected_tokens_{hr}"
    col2_name = f"%_tokens_input_{hr}"
    if col_name in eval_df.columns:
        df_std2.loc[hr, "avg_nb_selected_tokens"] = eval_df[col_name].std()
    else:
        df_std2.loc[hr, "avg_nb_selected_tokens"] = None
    if col2_name in eval_df.columns:
        df_std2.loc[hr, "avg_%_tokens_input"] = eval_df[col2_name].std()
    else:
        df_std2.loc[hr, "avg_%_tokens_input"] = None
df_std2

,comprehensiveness,sufficiency,combined,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.252638,0.143025,0.140285,10.134159,0.343498
elbow_kneedle,0.256844,0.157147,0.148549,7.237972,0.248250
elbow_dfdt,0.260049,0.139820,0.138776,9.239707,0.291749
elbow_lmethod,0.237732,0.180475,0.146362,2.055170,0.143145
top_n_3,0.222334,0.184198,0.138675,0.051299,0.131718
top_n_5,0.244063,0.155979,0.138428,0.218221,0.189348
top_n_10,0.247595,0.134831,0.133808,1.173044,0.242944
top_n_20,0.241923,0.101110,0.127235,4.596359,0.169215
threshold_0.1,0.238641,0.170441,0.144130,5.706739,0.208423
threshold_0.3,0.223229,0.195684,0.148734,3.951744,0.162217
threshold_0.5,0.200180,0.232904,0.155882,2.418433,0.114698
threshold_0.7,0.177466,0.294004,0.179008,1.147638,0.073941

In [20]:
df_avg = (df + df2) / 2
borda_count_hard_rationale(df_avg)

,comprehensiveness,sufficiency,combined,borda,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.454025,0.108840,0.672593,8,11.866139,0.519211
elbow_kneedle,0.449610,0.118650,0.665480,10,9.251236,0.425282
elbow_dfdt,0.480331,0.054684,0.712823,4,12.850313,0.581290
elbow_lmethod,0.346751,0.196075,0.575338,16,3.923673,0.216972
top_n_3,0.303461,0.208026,0.547717,20,2.997857,0.179972
top_n_5,0.386616,0.161427,0.612595,14,4.980547,0.294692
top_n_10,0.461966,0.084536,0.688715,6,9.694197,0.541499
top_n_20,0.520148,0.001902,0.759123,2,16.909001,0.843851
threshold_0.1,0.423379,0.158407,0.632486,12,7.234257,0.336182
threshold_0.3,0.341785,0.202985,0.569400,18,4.646719,0.224686
threshold_0.5,0.256936,0.246315,0.505311,22,2.687438,0.137705
threshold_0.7,0.184192,0.311816,0.436188,24,1.397626,0.078591

In [21]:
df_std_avg = (df_std + df_std2) / 2
df_std_avg

,comprehensiveness,sufficiency,combined,avg_nb_selected_tokens,avg_%_tokens_input
elbow_simple-lmethod,0.291259,0.252147,0.175516,10.519031,0.344941
elbow_kneedle,0.283494,0.257282,0.176139,7.487127,0.249704
elbow_dfdt,0.287156,0.242203,0.177076,9.589843,0.295963
elbow_lmethod,0.277545,0.256987,0.181715,1.992631,0.137746
top_n_3,0.268851,0.259662,0.180680,0.045937,0.125514
top_n_5,0.279961,0.246075,0.180174,0.195846,0.183258
top_n_10,0.264803,0.228871,0.154479,1.102737,0.240798
top_n_20,0.267139,0.150075,0.137361,4.461758,0.176045
threshold_0.1,0.265496,0.255938,0.165394,5.677667,0.201051
threshold_0.3,0.263467,0.265011,0.181069,3.872330,0.154449
threshold_0.5,0.247704,0.284266,0.189617,2.259900,0.105748
threshold_0.7,0.224388,0.316401,0.199927,1.084951,0.070244

In [58]:
model_pred_col = "Camelbert-MSA"
model_pred_col2 = "AraBert"
runtime_df = pd.read_csv("data/hard_rationale/hard_rationale_runtime_" + model_pred_col + ".csv")
runtime_df2 = pd.read_csv("data/hard_rationale/hard_rationale_runtime_" + model_pred_col2 + ".csv")

In [59]:
runtime_df.index = runtime_df["method"]
runtime_df.drop(columns=["method"], inplace=True)
runtime_df2.index = runtime_df2["method"]
runtime_df2.drop(columns=["method"], inplace=True)

In [60]:
runtime_df_avg = (runtime_df + runtime_df2) / 2
runtime_df_avg

                       mean         std
method
dfdt             423.032284  177.047834
kneedle          194.497056   93.832102
lmethod         1268.635704  569.390614
simple-lmethod    42.408232   19.983065
threshold-0.1     10.357188    4.510920
threshold-0.3     10.780252    4.198846
threshold-0.5     10.924276    4.170947
threshold-0.7     10.401222    4.200176
top-10            10.031382    4.264743
top-20             9.743482    4.393307
top-3              9.736189    4.238042
top-5             10.270673    3.886225